server:
  port: 9999
  context-path: /oauthservice

logging:
  level:
    root: DEBUG
spring:
  redis:
    host: 127.0.0.1
    port: 6379
  application:
    name: Oauth2Server
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
      username: wangab
      password: wab123